service: black-angus-lambda

plugins:
  - serverless-offline
  - serverless-secrets
  - serverless-python-requirements
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/**
    - .serverless/**
    - .mypy_cache/**
    - .pytest_cache/**

provider:
  name: aws
  stage: tokyo
  runtime: python3.9
  region: ${param:region}
  architecture: ${param:architecture}

params:
  tokyo:
    region: 'ap-northeast-1'
    architecture: 'arm64'
    docker_architecture: ['--platform', 'linux/arm64/v8']
  seoul:
    region: 'ap-northeast-2'
    architecture: 'x86_64'
    docker_architecture: ['--platform', 'linux/amd64']

custom:
  pythonRequirements:
    # disable cache cause of each region using different architecture
    useDownloadCache: false
    useStaticCache: false
    dockerizePip: non-linux
    dockerImage: public.ecr.aws/sam/emulation-python3.9:latest
    dockerRunCmdExtraArgs: ${param:docker_architecture}
    zip: false

functions:
  index:
    memorySize: 512
    timeout: 5
    handler: app.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
